// Bolivia provinces organized by departments
export const BOLIVIA_PROVINCES = {
  la_paz: [
    { value: "murillo", label: "Murillo" },
    { value: "omasuyos", label: "Omasuyos" },
    { value: "pacajes", label: "Pacajes" },
    { value: "camacho", label: "Camacho" },
    { value: "muñecas", label: "Muñecas" },
    { value: "larecaja", label: "Larecaja" },
    { value: "franz_tamayo", label: "Franz Tamayo" },
    { value: "ingavi", label: "Ingavi" },
    { value: "los_andes", label: "Los Andes" },
    { value: "aroma", label: "Aroma" },
    { value: "nor_yungas", label: "Nor Yungas" },
    { value: "sud_yungas", label: "Sud Yungas" },
    { value: "inquisivi", label: "Inquisivi" },
    { value: "loayza", label: "Loayza" },
    { value: "caranavi", label: "Caranavi" },
    { value: "gualberto_villarroel", label: "Gualberto Villarroel" },
    { value: "jose_manuel_pando", label: "José Manuel Pando" },
    { value: "manco_kapac", label: "Manco Kapac" },
    { value: "abel_iturralde", label: "Abel Iturralde" },
    { value: "bautista_saavedra", label: "Bautista Saavedra" },
  ],
  santa_cruz: [
    { value: "andres_ibañez", label: "Andrés Ibáñez" },
    { value: "warnes", label: "Warnes" },
    { value: "sara", label: "Sara" },
    { value: "ichilo", label: "Ichilo" },
    { value: "chiquitos", label: "Chiquitos" },
    { value: "sandoval", label: "Sandoval" },
    { value: "german_busch", label: "Germán Busch" },
    { value: "guarayos", label: "Guarayos" },
    { value: "cordillera", label: "Cordillera" },
    { value: "vallegrande", label: "Vallegrande" },
    { value: "florida", label: "Florida" },
    { value: "camiri", label: "Camiri" },
    { value: "ignacio_warnes", label: "Ignacio Warnes" },
    { value: "obispo_santiestevan", label: "Obispo Santiestévan" },
  ],
  cochabamba: [
    { value: "cercado", label: "Cercado" },
    { value: "campero", label: "Campero" },
    { value: "ayopaya", label: "Ayopaya" },
    { value: "esteban_arze", label: "Esteban Arze" },
    { value: "arque", label: "Arque" },
    { value: "capinota", label: "Capinota" },
    { value: "quillacollo", label: "Quillacollo" },
    { value: "jordan", label: "Jordán" },
    { value: "punata", label: "Punata" },
    { value: "tiraque", label: "Tiraque" },
    { value: "carrasco_cochabamba", label: "Carrasco" },
    { value: "chapare", label: "Chapare" },
    { value: "mizque", label: "Mizque" },
    { value: "aiquile", label: "Aiquile" },
    { value: "bolivar_cochabamba", label: "Bolívar" },
    { value: "tapacare", label: "Tapacarí" },
  ],
  sucre: [
    { value: "oropeza", label: "Oropeza" },
    { value: "yamparaez", label: "Yamparáez" },
    { value: "nor_cinti", label: "Nor Cinti" },
    { value: "sud_cinti", label: "Sud Cinti" },
    { value: "belisario_boeto", label: "Belisario Boeto" },
    { value: "tomina", label: "Tomina" },
    { value: "hernando_siles", label: "Hernando Siles" },
    { value: "luis_calvo", label: "Luis Calvo" },
    { value: "azurduy", label: "Azurduy" },
    { value: "zudañez", label: "Zudañez" },
  ],
  oruro: [
    { value: "cercado_oruro", label: "Cercado" },
    { value: "eduardo_avaroa", label: "Eduardo Avaroa" },
    { value: "carangas", label: "Carangas" },
    { value: "sajama", label: "Sajama" },
    { value: "litoral", label: "Litoral" },
    { value: "poopo", label: "Poopó" },
    { value: "pantaleón_dalence", label: "Pantaleón Dalence" },
    { value: "ladislao_cabrera", label: "Ladislao Cabrera" },
    { value: "saucarí", label: "Saucarí" },
    { value: "sebastian_pagador", label: "Sebastián Pagador" },
    { value: "tomas_barron", label: "Tomás Barrón" },
    { value: "sur_carangas", label: "Sur Carangas" },
    { value: "mejillones", label: "Mejillones" },
    { value: "nor_carangas", label: "Nor Carangas" },
    { value: "sabaya", label: "Sabaya" },
  ],
  potosi: [
    { value: "tomas_frias", label: "Tomás Frías" },
    { value: "rafael_bustillo", label: "Rafael Bustillo" },
    { value: "cornelio_saavedra", label: "Cornelio Saavedra" },
    { value: "chayanta", label: "Chayanta" },
    { value: "charcas", label: "Charcas" },
    { value: "alonso_de_ibañez", label: "Alonso de Ibáñez" },
    { value: "bernardino_bilbao", label: "Bernardino Bilbao" },
    { value: "antonio_quijarro", label: "Antonio Quijarro" },
    { value: "jose_maria_linares", label: "José María Linares" },
    { value: "nor_lipez", label: "Nor Lípez" },
    { value: "sur_lipez", label: "Sur Lípez" },
    { value: "daniel_campos", label: "Daniel Campos" },
    { value: "modesto_omiste", label: "Modesto Omiste" },
    { value: "enrique_baldivieso", label: "Enrique Baldivieso" },
    { value: "sud_chichas", label: "Sud Chichas" },
    { value: "nor_chichas", label: "Nor Chichas" },
  ],
  tarija: [
    { value: "cercado_tarija", label: "Cercado" },
    { value: "arce", label: "Arce" },
    { value: "gran_chaco", label: "Gran Chaco" },
    { value: "avilés", label: "Avilés" },
    { value: "méndez", label: "Méndez" },
    { value: "o_connor", label: "O'Connor" },
  ],
  beni: [
    { value: "cercado_beni", label: "Cercado" },
    { value: "vaca_diez", label: "Vaca Díez" },
    { value: "jose_ballivian", label: "José Ballivián" },
    { value: "yacuma", label: "Yacuma" },
    { value: "moxos", label: "Moxos" },
    { value: "mamore", label: "Mamoré" },
    { value: "itenez", label: "Iténez" },
    { value: "marbán", label: "Marbán" },
  ],
  pando: [
    { value: "nicolas_suarez", label: "Nicolás Suárez" },
    { value: "manuripi", label: "Manuripi" },
    { value: "madre_de_dios", label: "Madre de Dios" },
    { value: "abuna", label: "Abuná" },
    { value: "federico_roman", label: "Federico Román" },
  ],
} as const;

// Helper function to get provinces for a department
export const getProvincesForDepartment = (department: string) => {
  return BOLIVIA_PROVINCES[department as keyof typeof BOLIVIA_PROVINCES] || [];
};

// Department labels for display
export const DEPARTMENT_LABELS = {
  la_paz: "La Paz",
  santa_cruz: "Santa Cruz",
  cochabamba: "Cochabamba",
  sucre: "Sucre",
  oruro: "Oruro",
  potosi: "Potosí",
  tarija: "Tarija",
  beni: "Beni",
  pando: "Pando",
} as const;
